update inspection: check redundant class field doc comment
funivan/PhpClean pull request #113
Opened 2020-10-01 21:18 UTC by ChrisGalliano

2020-10-02 05:36 UTC, funivan requested changes

2020-10-02 05:36 UTC, funivan commented on src/main/kotlin/com/funivan/idea/phpClean/inspections/redundantDocCommentTag/RedundantDocCommentTagInspection.kt
> +                    for (paramTag in comment.paramTags) {
Why you are collecting items, and then iterate over this collection. Maybe you can parameter types immediately?
```kotlin
for (paramTag in comment.paramTags) {
   checkComment(paramTag, field. declaredType)
}
```

2020-10-05 14:54 UTC, funivan approved these changes
LGTM. Can I merge it?

2020-10-05 15:05 UTC, ChrisGalliano commented
Yes. Should I add something to change notes?

2020-10-05 17:29 UTC, funivan commented
> Yes. Should I add something to change notes?

Yes. this would be great.

2020-10-06 18:42 UTC, merged